### ISSUE TITLE
Version links in readme are broken

### ISSUE THREAD

**Issue by zenspider** [rubyreferences/rubychanges#25]
I think you want `s/html/md/g`

**Comment by zverok** [comment]
Generally, the README is designed to be rendered properly on the site itself: https://rubyreferences.github.io/rubychanges/ (where `.html` is what should be), but I agree it brings a confusion.
I'll think what to do about it (probably separate the README on GitHub from site's index)

**Comment by Maumagnaguagno** [comment]
I think all ``.md`` links are automatically translated to ``.html``, see [this](https://github.blog/2016-12-05-relative-links-for-github-pages/).
I can send a PR with the README links changed if you want.

**Comment by zverok** [comment]
I fixed the problem by separating README.md visible in GitHub and index.md rendered as a site's root.
