### ISSUE TITLE
Formatting is broken for Ruby 3.1 Thread::Backtrace.limit

### ISSUE THREAD

**Issue by nertzy** [rubyreferences/rubychanges#32]
See https://rubyreferences.github.io/rubychanges/3.1.html#threadbacktracelimit

<img width="873" alt="Screen Shot 2022-01-09 at 10 53 08 AM" src="https://user-images.githubusercontent.com/2488/148692224-ddc083b5-7151-45fd-87a6-6bfdb7492ce5.png">

**Comment by zverok** [comment]
Thanks, fixed! Some weird glitch with `-1` at the beginning of the line in Markdown rendering.
