### ISSUE TITLE
Broken HTML around the Dir changes

### ISSUE THREAD

**Issue by janko** [rubyreferences/rubychanges#4]
<img width="893" alt="screenshot 2018-12-29 at 13 35 56" src="https://user-images.githubusercontent.com/795488/50538360-daff8e00-0b6e-11e9-9936-77dbc18a32b1.png">

I would send a PR, but I'm not sure exactly what is the relationship between `2.6.0.md` and `_src/2.6.0.md`. I'm guessing the former is generated from the latter? In that case this might be a bug in Kramdown.

**Comment by zverok** [comment]
Fixed, thanks! Currently, _src/2.6.md is converted with super-ugly Regexp-based `postprocess.rb` (described here: https://rubyreferences.github.io/rubychanges/Contributing.html), I fixed it!
