### ISSUE TITLE
Function composition does not work

### ISSUE THREAD

**Issue by choosen** [rubyreferences/rubychanges#48]
https://github.com/rubyreferences/rubychanges/blob/master/_src/2.6.md?plain=1#L247

I tested it on 
irb(main):117:0> RUBY_VERSION
=> "2.6.9"

I had to wrap additionally all compositions with `&(  function1 >> function2  )`

Side Note: Faraday is weird and does not have method get, but it respond to it when send ... 

Worked for me:
```
res = URLS.map(& (->(url) { Faraday.get url } >> :body.to_proc >> JSON.method(:parse) >> ->(data) { data.fetch('urls').map { |u| u['id'] } } ) )
```

**Comment by zverok** [comment]
Interesting, it works for me:
```ruby
RUBY_VERSION
# => "2.6.3" / also tried on 2.7.1
Faraday::VERSION
# => "2.3.0" / also tried with the older I have, 1.4.2
%w[https://google.com https://github.com].map(&Faraday.method(:get) >> :body.to_proc >> ->(body) { body[0...20] })
# => ["<HTML><HEAD><meta ht", "\n\n\n\n\n\n<!DOCTYPE HTML"]
# This works, too, in case the difference was around the first lambda:
%w[https://google.com https://github.com].map(&->(url) { Faraday.get(url) } >> :body.to_proc >> ->(body) { body[0...20] })
# => ["<HTML><HEAD><meta ht", "\n\n\n\n\n\n<!DOCTYPE html"]
```
(I simplified the example a bit to work with generic sites, but the idea stays the same)

What problems did you have with the original syntax?..

**Comment by choosen** [comment]
oh my mistake.
my Faraday was 1.3.0

on 2.x works well.

by changing to block I skipped `&` at the beggining  and it did not work.
But I don't have to wrap it with parenthesis. 

So every things looks well  (for Faraday 2.0 :D  and shows well how to use class method)

Thanks for this example !
